name: Github Action
on: [push]
jobs:
    buildApp:
        runs-on: ubuntu-latest
        outputs:
            text: ${{ steps.finished.outputs.text }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install node_modules
              run: npm install
            - name: Build the project
              run: npm run build
            - name: Setup finish
              id: finished
              run: echo "::set-output name=text::hello-world-from-build-job"
    test-app:
        needs: buildApp
        runs-on: ubuntu-latest
        env:
            MY_JOB_OUTOUT: ${{ needs.buildApp.outputs.text }}
        steps:
            - name: Testing the dependent job
              run: echo $MY_JOB_OUTOUT
            
              