name: Github Action
on: [push]
jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install node_modules
              run: npm install
            - name: Build the project
              run: npm run build
            - name: Setup finish
              run: echo "Done!"
    test-app:
        needs: build-app
        runs-on: ubuntu-latest
        steps:
            - name: Testing the dependent job
              run: echo "This will run after build-app"
            
              